### ISSUE TITLE
Add a feature to create pie chart based on the input given

### ISSUE THREAD

**Issue by thelavenderhue** [opencodeiiita/Productivity-Tracker#106]
Add a feature to create pie chart based on the input given in the form of activity name and time schedule. For example, the user will input different tasks for different time intervals. Based on that, a pie chart will be generated which will show the time spent on each activity.

**Comment by thelavenderhue** [comment]
@Ksathwik03 you have already worked on this repository once, we want to ensure everyone is getting a chance

**Comment by Ksathwik03** [comment]
> @Ksathwik03 you have already worked on this repository once, we want to ensure everyone is getting a chance

Sure mam 🙌.
But does that mean i will never be able to claim any other issue in this repo.
