### ISSUE TITLE
Implement authentication using Google

### ISSUE THREAD

**Issue by untrulynoxiusmj** [opencodeiiita/Productivity-Tracker#39]
You will need to solve this issue first : 
https://github.com/opencodeiiita/Productivity-Tracker/issues/13

Add Client ID and secret in /backend/config/keys.js
This file has been added in .gitignore

There is a Sign In with google button added in Fronted
Clicking on that should redirect client to Google Login Page

/auth/google and /auth/google/callback routes need to be implemented,

Database connection and User schema have been added.
Store User in the database according to the schema

You may want to use Passport http://www.passportjs.org/

**Comment by karankc23** [comment]
Claim

**Comment by Tanushree-coder** [comment]
claim

**Comment by D-Big-B** [comment]
claim

**Comment by D-Big-B** [comment]
@untrulynoxiusmj  sir is this issue open for all?
Can I start working on it?
