### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by thelavenderhue** [opencodeiiita/Productivity-Tracker#4]
Add a footer relevant to the project by following the color palette

**Comment by batflarrow** [comment]
Claim

**Comment by prxtikk-18** [comment]
claim

**Comment by mayank-kr** [comment]
Claim

**Comment by shlesh** [comment]
claim

**Comment by batflarrow** [comment]
Hey @thelavenderhue What links should i have in the footer..?

**Comment by thelavenderhue** [comment]
@batflarrow Just add relevant ones, a logo, copyright, link to homepage, some other social media platforms (don't necessarily have to link all)

**Comment by batflarrow** [comment]
> @batflarrow Just add relevant ones, a logo, copyright, link to homepage, some other social media platforms (don't necessarily have to link all)

Ohk great, thanks!
