### ISSUE TITLE
Add Timer

### ISSUE THREAD

**Issue by thelavenderhue** [opencodeiiita/Productivity-Tracker#54]
Create a new route for timer and add a feature to set timer for a particular amount of time. As soon as the timer reaches 00:00, an alarm should ring/notification should be generated. A user can add different tasks and notes associated with each of them and as soon as the timer reaches 0, that task should be marked as completed. There should also be a setting to set the number of times the timer should run for one task.

For reference, refer to the following website:
[https://pomofocus.io/](https://pomofocus.io/)

Note: You don't have to create the exact replica, use your own creativity for styling.

**Comment by Tanushree-coder** [comment]
claim

**Comment by Ksathwik03** [comment]
@thelavenderhue mam since 4 days are completed i would like to work on this.
