### ISSUE TITLE
Login Remains 

### ISSUE THREAD

**Issue by Ksathwik03** [opencodeiiita/Productivity-Tracker#7]
In the Nav bar there is no logout when some one logins and profile is not visible. I would like to do the frontend and the backend for this .

**Comment by jalanprakhar** [comment]
claim

**Comment by untrulynoxiusmj** [comment]
@Ksathwik03 the issue you are referring to will be opened soon at an appropriate time and can be claimed only then.
I am closing this issue for now.

**Comment by Ksathwik03** [comment]
> @Ksathwik03 the issue you are referring to will be opened soon at an appropriate time and can be claimed only then. I am closing this issue for now.

Sir i am not saying writing the complete login functionality for now the islogin functionality returns false all the time when it returns true the navbar changes from login to logout and profile is also visible is navbar this is small task but since i did the navbar i wanted to add this but pr got merged hence i just want you to reconsider this issue.
