### ISSUE TITLE
Make the website responsive

### ISSUE THREAD

**Issue by thelavenderhue** [opencodeiiita/Productivity-Tracker#72]
Attached here are the screenshots of how the components get destructured when changing the width or height.
Correct that.
![image2](https://user-images.githubusercontent.com/58396051/136927437-3653752b-d9d1-4071-b806-ab11961d91f9.jpeg)
![image1](https://user-images.githubusercontent.com/58396051/136927440-921f274d-5960-4c66-a8e3-2a948215cd67.jpeg)

**Comment by hotblooded058** [comment]
claim
