### ISSUE TITLE
POST /note

### ISSUE THREAD

**Issue by untrulynoxiusmj** [opencodeiiita/Productivity-Tracker#80]
Add POST /note route to create a new note
You may use a dummy user or the authenticated user

Add /backend/config/keys.js file in the following format : `module.exports = { google : { clientId : '*****', clientSecret : '*****' }, session : { cookieKey : "somesecretsauce" } }`

Refer note schema for required fields
user_id : id of the user creating the note (authenticated user)
title : title of note
text : description of note

Ask doubts on discord

**Comment by Tanushree-coder** [comment]
claim

**Comment by Tanushree-coder** [comment]
Sorry sir, I'm not getting idea about this issue, I'm unassigning myself. Please assign it to someone else.

**Comment by shlesh** [comment]
would like to work on this

**Comment by schandu-eng** [comment]
> comment below to claim this issue
> Only the new comments will be considered (i.e. after this comment)

Claim
