### ISSUE TITLE
POST /task

### ISSUE THREAD

**Issue by untrulynoxiusmj** [opencodeiiita/Productivity-Tracker#81]
Add POST /task route to create a new task

Add /backend/config/keys.js file in the following format : `module.exports = { google : { clientId : '*****', clientSecret : '*****' }, session : { cookieKey : "somesecretsauce" } }`

Refer task schema for required fields
user_id : id of the user creating the task (authenticated user)
description : description of task
times : array `times:[{
        HH: Number,
        MM: Number,
        SS: Number,
    }]`

Ask doubts on discord

**Comment by Puja-Saraf** [comment]
claim

**Comment by ashutosh3027** [comment]
claim

**Comment by abhi9-hash** [comment]
claim 
if it is still open i want to work on it
