### ISSUE TITLE
POST /todo

### ISSUE THREAD

**Issue by untrulynoxiusmj** [opencodeiiita/Productivity-Tracker#82]
Add POST /todo route to create a new todo

Add /backend/config/keys.js file in the following format : `module.exports = { google : { clientId : '*****', clientSecret : '*****' }, session : { cookieKey : "somesecretsauce" } }`

Refer todo schema for required fields
user_id : id of the user creating the todo(authenticated user)
description : description of todo
checked : boolean `(True or False)`

Ask doubts on discord

**Comment by shashwat-mittal** [comment]
claim

**Comment by varunKT001** [comment]
Claim

**Comment by abhi9-hash** [comment]
claim

**Comment by shashwat-mittal** [comment]
Sir may you please unassign this issue as I am unable to do it

**Comment by untrulynoxiusmj** [comment]
> Sir may you please unassign this issue as I am unable to do it

@shashwat-mittal you can ask doubts on discord.
Please share the problem you are facing

**Comment by abhi9-hash** [comment]
Claim

**Comment by adtoria** [comment]
Claim

**Comment by VineethKumarM** [comment]
Claim

**Comment by untrulynoxiusmj** [comment]
@abhi9-hash any updates?
